apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: boardgame-deployment
spec:
  selector:
    matchLabels:
      app: boardgame
      #env: test
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: boardgame
       #env: test
    spec:
      containers:
        - name: boardgame
          image: deepthinker07/bgimg:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: boardgame-ssvc
spec:
  selector:
    app: boardgame # selects the Pods that the Service will route traffic to, based on matching labels.
  ports:
    - protocol: "TCP"
      port: 80 # clusterIP port [port on which the Service is exposed within the cluster]
      targetPort: 8080 # container port
  type: LoadBalancer # type of the service.